### ISSUE TITLE
The weight of the linear layer

### ISSUE THREAD

**Issue by Richar-Du** [SALT-NLP/LLaVAR#1]
Thanks for your awesome work! The paper states that both the linear layer and the LLM are fine-tuned, but I can not find the link to the weight of the linear layer. Would you mind sharing it? Thanks in advance :)

**Comment by StevenyzZhang** [comment]
Thanks for your interest!
The weight for the linear layer is contained in the released delta weight:
![image](https://github.com/SALT-NLP/LLaVAR/assets/51267590/104d542e-8d6e-41bf-a841-5dcbd1d1902a)

Using the command below should give you all the model weights except the frozen visual encoder (openai/clip-vit-large-patch14-336), which will be tagged with `device.type == 'meta'` and automatically downloaded when you load the model (Check /LLaVAR/LLaVA/llava/eval/run_llava.py)
```
python3 /LLaVAR/LLaVA/model/apply_delta.py \
    --base /Path/to/LLaMA/13B \
    --target /Path/to/Merged/LLaVAR \
    --delta  /Path/to/LLaVAR_delta
```
