### ISSUE TITLE
Great work! Could you plz release the pretraining checkpoint for LLaVAR?

### ISSUE THREAD

**Issue by SZhanZ** [SALT-NLP/LLaVAR#11]
Hello, I wanna test the ability of LLaVAR's pretraining model, but I only find the final weights for LLaVAR. Could you release the pretraining checkpoint for LLaVAR?

Thanks in advance~

**Comment by StevenyzZhang** [comment]
Hi:

I have uploaded the pretrained multimodal projector [here](https://huggingface.co/SALT-NLP/LLaVAR_delta/blob/main/llavar-13b-pretrain.bin). 

This is the original pretrained version used in the paper (a bit outdated). It should work well with CLIP-L/14-336, Vicuna-13B v1.1.
