### ISSUE TITLE
using llavar

### ISSUE THREAD

**Issue by baroninn** [SALT-NLP/LLaVAR#17]
maybe a dumb question,
I tried LlaVa and it did not succeed in processing text, so I found this LlaVar model. Which might be exactly what im looking for.
just wondering how I should run it.

do you load it up with Gradio ? or ?
could you provide some insights into using the llavar model.

**Comment by StevenyzZhang** [comment]
We provide the snapshot of the LLaVA codebase we used in this repo (the llava folder, is kind of outdated now). You can host it via Gradio following the instructions.

**Comment by baroninn** [comment]
Hi Steven,
Thank you for your answer :-)
not sure if you read it right, but I mentioned LLaVar,,,, ((notice the "r" at the end).
did your answer take that into account ?
if so , then I will take a look at this better.
Im only asking because the llava model had some difficulty understanding numbers on an Icelandic Invoice.... But it did alright with numbers on an english invoice.
So, its my understanding that LLaVar (with an rrrr :-) is a model that is better with text and numbers.

trying to figure out where and how I can try out that LLaVar.

**Comment by StevenyzZhang** [comment]
Hi, thanks for the follow-up.
The current release of LLaVAR uses the same architecture as LLaVA. So, hosting LLaVAR should be similar to hosting LLaVA. All you need is to change the model checkpoint you used. You can find more details in the README and other issues.
