### ISSUE TITLE
Error in paper

### ISSUE THREAD

**Issue by shipengai** [SALT-NLP/LLaVAR#18]
In Appendix A of paper， There are same sentences
In Section CLIP-based categorization，
Ad & Product Packaging: “ad”, “advertisement”, “food packaging”, “product packaging”.
Educational Material: “ad”, “advertisement”, “food packaging”, “product packaging”.

**Comment by StevenyzZhang** [comment]
Thanks for pointing this out, the correct one should be:
Educational Material: "exam paper", "quiz", "certificate", "book page"
