### ISSUE TITLE
Output Difference between Demo and Local Setup

### ISSUE THREAD

**Issue by aszala** [SALT-NLP/LLaVAR#2]
Hello, is there any difference between the demo and released weights/codes in Github?

I tried to reproduce the results I get from the demo, however, my local output is different.

I download the LLama13B weights and merge them with your provided delta weights following LLaVA. Then I rename the folder to include "v1" and set the conv mode to "llava_v1".

Is there something I did incorrectly? or is there some difference between the demo/GitHub?

Thanks!

**Comment by StevenyzZhang** [comment]
Thanks for trying out our demo and weights. There is no difference between the demo/GitHub.

Which script are you using for your local reproduction?

Other than the conv mode, image preprocessing could be another thing you can check for differences.

If you are using `LLaVAR/LLaVA/llava/eval/run_llava.py`, the image processing is by default `resize_image()`.

If you are using the controller/web_server/model_worker in the `/LLaVAR/LLaVA/llava/serve` folder, the image preprocessing is specified by the user (Crop, resize, and pad), which is implemented in get_images() in `LLaVAR/LLaVA/llava/conversation.py`

I hope this is helpful. Feel free to share more information if the problem remains.
