### ISSUE TITLE
could you please release original data 

### ISSUE THREAD

**Issue by GITMrzk** [SALT-NLP/LLaVAR#3]
The currently released data are all compressed with the short side 384. Is there a corresponding original image?

**Comment by GITMrzk** [comment]
maybe i can get LAION-5B first, then find the corresponding image by id?

**Comment by GITMrzk** [comment]
> maybe i can get LAION-5B first, then find the corresponding image by id?

takes up too much space

**Comment by StevenyzZhang** [comment]
As you mentioned, it might take too much space to release the original images.
We plan to release the original image URL and other metadata (from LAION-5B) in the next few weeks, stay tuned!

**Comment by StevenyzZhang** [comment]
The meta data (URL, caption, ...) of used images is released now. You can download the high res version if you want.
