### ISSUE TITLE
pytorch_model-00002-of-00003.bin - Access denied

### ISSUE THREAD

**Issue by petermcc0807** [SALT-NLP/LLaVAR#4]
Hi,

For the past couple of days, I've been trying to download the model weight delta using Python's gdown.

I've downloaded all files except for pytorch_model-00002-of-00003.bin. When I try to download it directly:

`gdown https://drive.google.com/uc?id=1S2bgHQSFL7deBuVF_Z1ReG7KQyz0m_kt`

I keep getting the following:

> Access denied with the following error:
> 
> Too many users have viewed or downloaded this file recently. Please
> try accessing the file again later. If the file you are trying to
> access is particularly large or is shared with many people, it may
> take up to 24 hours to be able to view or download the file. If you
> still can't access a file after 24 hours, contact your domain
> administrator.

Is there a way to resolve this quickly? Or perhaps move all files over to Hugging Face?

Thanks.

**Comment by StevenyzZhang** [comment]
Hi! Thanks for pointing this out!

The model checkpoint is now on [huggingface](https://huggingface.co/SALT-NLP/LLaVAR_delta/tree/main).

**Comment by petermcc0807** [comment]
Hi,

Sorry for the delayed reply. Many thanks for uploading to Hugging Face!
