### ISSUE TITLE
Great work! what is the correct name for model name?

### ISSUE THREAD

**Issue by WilTay1** [SALT-NLP/LLaVAR#7]
![image](https://github.com/SALT-NLP/LLaVAR/assets/133484736/9e9f061b-9180-47c1-95d8-46dabeb7b292)

Should I use some specific name for this model name parameter? Thanks.

**Comment by StevenyzZhang** [comment]
There is no specific requirement for this. We recommend including "v1" into the name to use the "llava_v1" conversation mode.

This is how run_llava.py select conversation mode:

<img width="258" alt="image" src="https://github.com/SALT-NLP/LLaVAR/assets/51267590/b2dc278e-b47f-403c-be91-987e82ce52ec">

Using something like `llavar_v1` should be fine.
